language: generic
deploy:
install:
before_script:
script:

notifications:
  webhooks:
    urls:
      - https://two-carrots-study.loca.lt/api/deployment/283683da-cdc0-4e77-b7dc-2b689cb36082
    on_success: always
    on_failure: never
    on_start:   never
    on_cancel:  never
    on_error:   never
