language: generic
deploy:
install:
before_script:
script:

notifications:
  webhooks:
    urls:
      - https://stale-ducks-speak.loca.lt/travis
    on_success: always
    on_failure: always
    on_start:   never
    on_cancel:  never
    on_error:   never
